config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#not_acceptable'
  get '/500', to: 'errors#internal_error'

  resources :allergens, only: :index do
    collection do
      get 'edit-families'
      post 'update-families'
    end
  end

  resources :allergen_families, only: [:index, :show]

  resources :products, only: [:index, :show] do
    resources :ingredients, only: :index
    resources :orders, only: [:create, :destroy]

    collection do
      get 'categories/:category', to: 'products#category', as: 'category'
    end
  end

  resources :orders, only: [:index, :show, :new, :create] do
    delete 'product_orders/:id', to: "orders#product_delete"
    resources :payments, only: [:new, :create]
    collection do
      get 'shopping_cart'
    end
  end
end

app/models/allergen.rb
class Allergen < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient, optional: true
  belongs_to :allergen_family, optional: true
end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
  before_action :fetch_allergen, only: [:destroy]

  def index
    @allergens = policy_scope(Allergen)
    @user = current_user if user_signed_in?
  end

  def edit_families
    # define the data to check the right allergens in the view
    @allergens = current_user.allergen_families
    authorize @allergens
  end

  def update_families
    # destroy the allergens
    current_user.allergen_families.destroy_all
    if params[:allergen].nil?
      @allergens = current_user.allergen_families
      authorize @allergens
      render :edit_families
      flash[:alert] = "Please select your allergy."
    else
      ids = params[:allergen][:allergen_families_ids]
      ids.each do |id|
        @allergen = Allergen.new(user: current_user, allergen_family_id: id)
        authorize @allergen
        @allergen.save
      end
      flash[:notice] = "You've saved your allergies!"
      redirect_to root_path
    end
  end

  private

  def fetch_allergens
    @allergens = policy_scope(Allergen)
    authorize @allergen
  end

  def allergen_params
    params.require(:allergen).permit(:allergen_type, allergen_families_ids: [])
  end
end

app/views/allergens/edit.html.erb
<h1>Your allergens</h1>

<%= simple_form_for(@allergens) do |f| %>
<div class="form-group">
  <label class="control-label check_boxes optional">Select your food restriction: </label>
  <div class="container-families">
      <input type="hidden" name="allergen[allergen_type]" value="family">
      <% AllergenFamily.all.each do |af| %>
      <div class="family">

        <%  @checked = af.allergens.include?(@allergen) ? "checked" : "" %>

        <input type="checkbox" class="hidden" value="<%= af.id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= af.id %>" <%= @checked %>>
        <label for="allergen_families_ids_<%= af.id %>">
          <%= af.name %>
        </label>
      </div>
    <% end %>
  </div>
</div>
  <!-- Inject categories here -->

  <%= f.submit "Start Shopping!", class: "btn btn-primary"  %>
<% end %>

app/views/allergens/edit_all.html.erb
<h1>Your allergens</h1>

<%= simple_form_for(@allergens) do |f| %>
<div class="form-group">
  <label class="control-label check_boxes optional">Select your food restriction: </label>
  <div class="container-families">
      <input type="hidden" name="allergen[allergen_type]" value="family">
      <% AllergenFamily.all.each do |af| %>
      <div class="family">

        <%  @checked = af.allergens.include?(@allergen) ? "checked" : "" %>

        <input type="checkbox" class="hidden" value="<%= af.id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= af.id %>" <%= @checked %>>
        <label for="allergen_families_ids_<%= af.id %>">
          <%= af.name %>
        </label>
      </div>
    <% end %>
  </div>
</div>
  <!-- Inject categories here -->

  <%= f.submit "Start Shopping!", class: "btn btn-primary"  %>
<% end %>

app/views/allergens/edit_families.html.erb
<div class="container pages-container">
  <h1>What are your allergies?</h1>
  <div class="separator"></div>
  <%= simple_form_for(Allergen.new, url: update_families_allergens_path) do |f| %>
    <div class="form-group">
      <label class="control-label check_boxes"><h4>Go ahead and select your food restrictions: </h4></label>
      <input type="hidden" name="post[category_ids][]" value="">
      <div class="family-choices">
        <div class="left-group">
          <!-- nuts -->
          <div class="family-box">
            <div class="hidden-icons 0 d-flex justify-content-center">
              <%= image_tag image_path('checked_icon.png'), class: "checked-icon"%>
            </div>
            <% if @allergens.present? %>
              <%  @checked = @allergens.pluck(:allergen_family_id).include?(AllergenFamily.all[0].id) ? "checked" : "" %>
            <% else %>
              <% @checked = "" %>
            <% end %>
            <input type="checkbox" class="d-none" value="<%= AllergenFamily.all[0].id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= AllergenFamily.all[0].id %>" <%= @checked %>>
            <label class="family-choice 0 left-choice" for="allergen_families_ids_<%= AllergenFamily.all[0].id %>">
            <%= image_tag image_path('peanuts_01.png'), class: "allergen-image" %><%= AllergenFamily.all[0].name.upcase %>
            </label>
          </div>
          <!-- lactose -->
          <div class="family-box">
            <div class="hidden-icons 1 d-flex justify-content-center">
              <%= image_tag image_path('checked_icon.png'), class: "checked-icon"%>
            </div>
            <% if @allergens.present? %>
              <%  @checked = @allergens.pluck(:allergen_family_id).include?(AllergenFamily.all[1].id) ? "checked" : "" %>
            <% else %>
              <% @checked = "" %>
            <% end %>
            <input type="checkbox" class="d-none" value="<%= AllergenFamily.all[1].id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= AllergenFamily.all[1].id %>" <%= @checked %>>
            <label class="family-choice 1 left-choice" for="allergen_families_ids_<%= AllergenFamily.all[1].id %>">
            <%= image_tag image_path('milk_01.png'), class: "allergen-image" %><%= AllergenFamily.all[1].name.upcase %>
            </label>
          </div>
          <!-- shellfish -->
          <div class="family-box">
            <div class="hidden-icons 2 d-flex justify-content-center">
              <%= image_tag image_path('checked_icon.png'), class: "checked-icon"%>
            </div>
            <% if @allergens.present? %>
              <%  @checked = @allergens.pluck(:allergen_family_id).include?(AllergenFamily.all[2].id) ? "checked" : "" %>
            <% else %>
              <% @checked = "" %>
            <% end %>
            <input type="checkbox" class="d-none" value="<%= AllergenFamily.all[2].id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= AllergenFamily.all[2].id %>" <%= @checked %>>
            <label class="family-choice 2 left-choice" for="allergen_families_ids_<%= AllergenFamily.all[2].id %>">
            <%= image_tag image_path('crab_01.png'), class: "allergen-image" %><%= AllergenFamily.all[2].name.upcase %>
            </label>
          </div>
          <!-- gluten -->
          <div class="family-box">
            <div class="hidden-icons 3 d-flex justify-content-center">
              <%= image_tag image_path('checked_icon.png'), class: "checked-icon"%>
            </div>
            <% if @allergens.present? %>
              <%  @checked = @allergens.pluck(:allergen_family_id).include?(AllergenFamily.all[3].id) ? "checked" : "" %>
            <% else %>
              <% @checked = "" %>
            <% end %>
            <input type="checkbox" class="d-none" value="<%= AllergenFamily.all[3].id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= AllergenFamily.all[3].id %>" <%= @checked %>>
            <label class="family-choice 3 left-choice" for="allergen_families_ids_<%= AllergenFamily.all[3].id %>">
            <%= image_tag image_path('gluten_01.png'), class: "allergen-image" %><%= AllergenFamily.all[3].name.upcase %>
            </label>
          </div>
        </div>
        <div class="right-group">
          <!-- fish&meat -->
          <div class="family-box">
            <div class="hidden-icons 4 d-flex justify-content-center">
              <%= image_tag image_path('checked_icon.png'), class: "checked-icon"%>
            </div>
            <% if @allergens.present? %>
              <%  @checked = @allergens.pluck(:allergen_family_id).include?(AllergenFamily.all[4].id) ? "checked" : "" %>
            <% else %>
              <% @checked = "" %>
            <% end %>
            <input type="checkbox" class="d-none" value="<%= AllergenFamily.all[4].id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= AllergenFamily.all[4].id %>" <%= @checked %>>
            <label class="family-choice 4 right-choice" for="allergen_families_ids_<%= AllergenFamily.all[4].id %>">
            <%= image_tag image_path('fish_01.png'), class: "allergen-image" %><%= AllergenFamily.all[4].name.upcase %>
            </label>
          </div>
          <!-- soy -->
          <div class="family-box">
            <div class="hidden-icons 5 d-flex justify-content-center">
              <%= image_tag image_path('checked_icon.png'), class: "checked-icon"%>
            </div>
            <% if @allergens.present? %>
              <%  @checked = @allergens.pluck(:allergen_family_id).include?(AllergenFamily.all[5].id) ? "checked" : "" %>
            <% else %>
              <% @checked = "" %>
            <% end %>
            <input type="checkbox" class="d-none" value="<%= AllergenFamily.all[5].id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= AllergenFamily.all[5].id %>" <%= @checked %>>
            <label class="family-choice 5 right-choice" for="allergen_families_ids_<%= AllergenFamily.all[5].id %>">
            <%= image_tag image_path('soybean_01.png'), class: "allergen-image" %><%= AllergenFamily.all[5].name.upcase %>
            </label>
          </div>
          <!-- seeds -->
          <div class="family-box">
            <div class="hidden-icons 6 d-flex justify-content-center">
              <%= image_tag image_path('checked_icon.png'), class: "checked-icon"%>
            </div>
            <% if @allergens.present? %>
              <%  @checked = @allergens.pluck(:allergen_family_id).include?(AllergenFamily.all[6].id) ? "checked" : "" %>
            <% else %>
              <% @checked = "" %>
            <% end %>
            <input type="checkbox" class="d-none" value="<%= AllergenFamily.all[6].id %>" name="allergen[allergen_families_ids][]" id="allergen_families_ids_<%= AllergenFamily.all[6].id %>" <%= @checked %>>
            <label class="family-choice 6 right-choice" for="allergen_families_ids_<%= AllergenFamily.all[6].id %>">
            <%= image_tag image_path('seeds_01.png'), class: "allergen-image" %><%= AllergenFamily.all[6].name.upcase %>
            </label>
          </div>
        </div>
      </div>
    </div>
    <!-- end of allergens -->

    <%= f.submit "Start Shopping!", class: "btn btn-bottom" %>
  <% end %>
</div>