config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#not_acceptable'
  get '/500', to: 'errors#internal_error'

  resources :allergens, only: :index do
    collection do
      get 'edit-families'
      post 'update-families'
    end
  end

  resources :allergen_families, only: [:index, :show]

  resources :products, only: [:index, :show] do
    resources :ingredients, only: :index
    resources :orders, only: [:create, :destroy]

    collection do
      get 'categories/:category', to: 'products#category', as: 'category'
    end
  end

  resources :orders, only: [:index, :show, :new, :create] do
    delete 'product_orders/:id', to: "orders#product_delete"
    resources :payments, only: [:new, :create]
    collection do
      get 'shopping_cart'
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <p> <%= notice %> </p>
    <button type="button" class="close mt-2" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <p> <%= alert %> </p>
    <button type="button" class="close mt-2" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag image_path('safebite_logo.png') %>
    <% end %>

    <% # if #home %>
      <li class="nav-item">
        <div class="search">
          <i class="flex-item search-icon fas fa-search"></i>
          <%#= image_tag image_path('Ellipse.png'), class: "search-icon" %>
          <%= simple_form_for Product.new, url: root_path, method: :get, html: {class: "flex-item"} do |f| %>
            <%= f.input :search, label: false, placeholder: "search", input_html: { class: "search-bar", value: session[:search] } %>
          <% end %>
        </div>
      </li>
    <% #end %>
      <button class="burguer-menu" type="button" id = "sidebarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>

</div>

app/views/shared/_sidebar.html.erb
<!--   <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
  <div id="sidebar">
    <ul class= "list-unstyled components">
      <% if user_signed_in? %>


        <!-- <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"> -->
          <li class ="active">
            <%= link_to "My Allergens", edit_families_allergens_path %>
          </li>
          <li>
            <%= link_to "My Basket", shopping_cart_orders_path %>
          </li>
          <li>
            <%= link_to "Product Categories", products_path %>
          </li>
          <li>
            <%= link_to "Edit Profile", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          </li>
          </div>
        <!-- </li> -->
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>