config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#not_acceptable'
  get '/500', to: 'errors#internal_error'

  resources :allergens, only: :index do
    collection do
      get 'edit-families'
      post 'update-families'
    end
  end

  resources :allergen_families, only: [:index, :show]

  resources :products, only: [:index, :show] do
    resources :ingredients, only: :index
    resources :orders, only: [:create, :destroy]

    collection do
      get 'categories/:category', to: 'products#category', as: 'category'
    end
  end

  resources :orders, only: [:index, :show, :new, :create] do
    delete 'product_orders/:id', to: "orders#product_delete"
    resources :payments, only: [:new, :create]
    collection do
      get 'shopping_cart'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents
  has_many :ingredients_products
  has_many :ingredients, through: :ingredients_products
  has_many :orders_products
  has_many :orders, through: :orders_products

  enum category: [:breakfast_and_cereal, :canned_goods_and_soups, :dairy_eggs_and_cheese, :frozen_foods, :grains_pasta_and_sides, :fruits_and_vegetables, :cookies_and_snacks, :meat_and_seafood, :beverages, :beer_wine_and_spirits]

  attr_reader :search

  def self.search_allergens(current_user)
    allergen_families_ids = current_user.allergen_families.pluck(:id)
    allergen_families_products_ids = Ingredient.joins(:ingredients_products)
                                               .where(allergen_family_id: allergen_families_ids)
                                               .pluck("ingredients_products.product_id")
    self.where.not(id: allergen_families_products_ids)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @products = policy_scope(Product.all)
    @categories = []
    @products.each do |product|
      @categories << product.category
    end
    @categories.uniq!
  end

  def category
    @products = Product.where(category: params[:category]).search_allergens(current_user)
    authorize @products
  end

  def show
    @product = Product.find(params[:id])
    authorize @product

    @quantity_in_pending_order = OrdersProduct.where(product: @product, order: current_user.pending_order_in_cart).first

    fetch_ingredients

    if @quantity_in_pending_order
      @quantity_in_pending_order = @quantity_in_pending_order.quantity
    else
      @quantity_in_pending_order = 0
    end

    @total_price = current_user.pending_order_in_cart.orders_products.where(product: @product).sum("(orders_products.price_cents * orders_products.quantity)/100")
  end

  private

  def fetch_ingredients
    @ingredients = []
    IngredientsProduct.where(product_id: @product).each do |ingredients_product|
      @ingredients << Ingredient.where(id: ingredients_product.ingredient_id).map(&:name).first.capitalize
    end
    return @ingredients
  end
end

app/views/products/category.html.erb
<div id="show-search-bar" class="container pages-container">
  <% if @products.any? %>
  <% else %>
    <h1>There are no products available acording to your allergens.</h1>
  <% end %>
  <h1> <%= @products.first.category.gsub(/_/, ' ').gsub(/and/, '&').capitalize if @products.first %> </h1>
</div>

  <% @products.each do |product| %>

    <div class="add-product-card d-flex">
      <div class="product-image-price">

        <%= link_to product_path(product) do %>

        <img src=<%= product.photo %> />
        <p><%= product.price %> €</p>
      </div>

      <div class="product-quantity">
          <h4> <%= product.name %> </h4>
          <p> <%= product.brand.capitalize %> </p>
      </div>

      <% end %>

      <div class="add-quantity d-flex flex-column justify-content-center">
          <%= link_to "+", product_orders_path(product), method: :post, remote: true, class: "add" %>
          <div class ="quantity" id="order_count_<%= product.id %>">
            <%= OrdersProduct.find_by(product: product, order: current_user.pending_order_in_cart)&.quantity || 0 %>
          </div>
          <%= link_to "-", product_order_path(product, 0), method: :delete, remote: true, class: "remove" %>
      </div>
    </div>
  </div>

  <% end %>

<div class="btn mt-5">
  <%= link_to "<", products_path, class: "btn btn-bottom-back" %>
  <%= link_to "Ready to checkout?", shopping_cart_orders_path, class: "btn btn-bottom-checkout" %>
</div>

app/views/products/index,.html.erb
<h1>Products#index,</h1>
<p>Find me in app/views/products/index,.html.erb</p>

app/views/products/index.html.erb
<div class="container py-4 category-message">
  <h1>We know you want to avoid <span style="color: #FC9233;"><%= current_user.allergen_families.map(&:name).to_sentence.gsub(/and/, '&') %></span>.</h1>

</div>

  <% @categories.each do |category| %>
    <%= link_to category_products_path(category) do %>
      <div class="category-card">
        <div id="category-image" style="background-image: url(<%= asset_path("#{category + '.jpg'}") %>)"></div>
        <div class="category-text">
          <h3> <%= category.gsub(/_/, ' ').gsub(/and/, '&').capitalize %> </h3>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/products/show.html.erb
<div class="container pages-container">
    <div class="row">
      <div class="col-sm-12">
        <h1><%= @product.name.capitalize %></h1>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="product-photo" style="background-image: url('<%= image_path(@product.photo) %>')"></div>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-12 product-info">
        <h2><%= @product.brand.capitalize %></h2>
        <h3><%= @product.category.gsub(/_/, ' ').gsub(/and/, '&').capitalize %></h3>
        <h4><%= @product.volume %></h4>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12 product-price">
        <p><strong><%= humanized_money_with_symbol(@product.price) %> per unit</strong></p>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-12 product-description">
        <p><strong>Description:</strong> <%= @product.description %></p>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-12 product-description">
        <p><strong>Ingredients:</strong>
          <%= @ingredients.to_sentence %>
        </p>
      </div>
    </div>

  </div>

</div>

<div class="container white-background pl-5 pr-5 pt-1 pb-5">
  <div class="row mt-3">
    <div class="col-sm-12 add-quantity d-flex align-self-center justify-content-between">
      <%= link_to "-", product_order_path(@product), method: :delete, remote: true, class: "remove" %>
      <p class="centered"><strong id="order_count_<%= @product.id %>"><%= @quantity_in_pending_order %></strong></p>
      <%= link_to "+", product_orders_path(@product), method: :post, remote: true, class: "add" %>
      <p class="centered"><strong>Total price: <span id="total_price_<%= @product.id %>"><%= @total_price %></span> €</strong></p>
  </div>
</div>

<div class="btn">
  <%= link_to "<", category_products_path(@product.category), class: "btn btn-bottom-back" %>
  <%= link_to "Ready to checkout?", shopping_cart_orders_path, class: "btn btn-bottom-checkout" %>
</div>